packages:
  - "."

allowBuilds:
  "@prisma/engines": true
  "@scarf/scarf": true
  esbuild: true
  "prisma": true

minimumReleaseAgeExclude:
  - tsx@4.23.4

overrides:
  fast-uri: 3.1.4
  js-yaml: 5.2.2
