export const API_CODE_BY_STATUS: Record<number, string> = {
  400: "VALIDATION_ERROR",
  401: "AUTHENTICATION_REQUIRED",
  403: "FORBIDDEN",
  404: "RESOURCE_NOT_FOUND",
  409: "RESOURCE_CONFLICT",
  422: "BUSINESS_RULE_VIOLATION",
  429: "RATE_LIMIT_EXCEEDED",
  500: "INTERNAL_ERROR",
  503: "SERVICE_UNAVAILABLE",
};

export const ApiCode = {
  NOT_FOUND: "RESOURCE_NOT_FOUND",
  CONFLICT: "RESOURCE_CONFLICT",
  UNAUTHORIZED: "AUTHENTICATION_REQUIRED",
  VALIDATION: "VALIDATION_ERROR",
  BUSINESS_RULE: "BUSINESS_RULE_VIOLATION",
} as const;
